Algoritmo "conversor de moedas"
//  
//  
// Descrição   : conversor de moedas! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/05/2020
Var
   valor1, valor2, valor: real


Inicio
      escreva("Informe o valor em Real:")
      leia(valor1)
      escreva("Informe o valor em Dólar:")
      leia(valor2)
      valor <- valor1 / valor2
      escreva("Você tem $:",valor, " Dólares")

Fimalgoritmo